### ISSUE TITLE
İsmail bey size ulaşmaya çalışıyorum nasıl ulaşabilirim.

### ISSUE THREAD

**Issue by tufancakiroglu** [ismail0234/bizimhesap-efatura-php-api#1]
İsmail bey size ulaşmaya çalışıyorum nasıl ulaşabilirim.

Emailim tufancakiroglu@cobunet.com müsait olduğunuzda dönüş yapar mısınız?

**Comment by ismail0234** [comment]
ismaiil_0234@hotmail.com adresine email atarsanız müsait olduğumda dönüş yapıyorum.

**Comment by tufancakiroglu** [comment]
Oraya mail gönderdim inceler misiniz? Sizinle çalışmak istiyoruz.

iPhone’umdan gönderildi

İsmail <notifications@github.com> şunları yazdı (8 Mar 2021 17:21):

﻿

ismaiil_0234@hotmail.com<mailto:ismaiil_0234@hotmail.com> adresine email atarsanız müsait olduğumda dönüş yapıyorum.

**Comment by ismail0234** [comment]
Emailiniz spam kutusuna düşmüş olabilir. Akşam kontrol edeceğim.

**Comment by tufancakiroglu** [comment]
Cep telefonunuzu da gönderebilirsiniz.

iPhone’umdan gönderildi

İsmail <notifications@github.com> şunları yazdı (8 Mar 2021 17:41):

﻿

Emailiniz spam kutusuna düşmüş olabilir. Akşam kontrol edeceğim.
